[build]
  command = "npm install --include=optional --no-save @rollup/rollup-linux-x64-gnu@4.59.0 @tailwindcss/oxide-linux-x64-gnu@4.1.12 lightningcss-linux-x64-gnu@1.30.1 && npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://global-lmg-production-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
